-- CREATE TASK

CREATE TABLE `test`.`t_Task`(
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_name` VARCHAR(200) NOT NULL,
  `task_param` TEXT NOT NULL,
  `insert_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP   ON  UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=INNODB;


